# Generated by Django 4.0.6 on 2022-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='abcd', upload_to='testimonilas/'),
            preserve_default=False,
        ),
    ]
