# Generated by Django 4.0.6 on 2022-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
